[2022-10-27 03:03:41,570] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.docker_command manual__2022-10-27T02:57:26.771756+00:00 [queued]>
[2022-10-27 03:03:41,583] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.docker_command manual__2022-10-27T02:57:26.771756+00:00 [queued]>
[2022-10-27 03:03:41,584] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 03:03:41,584] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-10-27 03:03:41,585] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 03:03:41,605] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): docker_command> on 2022-10-27 02:57:26.771756+00:00
[2022-10-27 03:03:41,612] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2022-10-27 03:03:41,617] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spark_job_dag', 'docker_command', 'manual__2022-10-27T02:57:26.771756+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmpvs2uug5t', '--error-file', '/tmp/tmpt68f3fb3']
[2022-10-27 03:03:41,619] {standard_task_runner.py:80} INFO - Job 83: Subtask docker_command
[2022-10-27 03:03:41,687] {task_command.py:369} INFO - Running <TaskInstance: spark_job_dag.docker_command manual__2022-10-27T02:57:26.771756+00:00 [running]> on host 972da7c49be0
[2022-10-27 03:03:41,789] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_job_dag
AIRFLOW_CTX_TASK_ID=docker_command
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T02:57:26.771756+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T02:57:26.771756+00:00
[2022-10-27 03:03:41,812] {docker.py:371} INFO - Pulling docker image bde2020/spark-master:latest
[2022-10-27 03:03:47,303] {docker.py:385} INFO - latest: Pulling from bde2020/spark-master
[2022-10-27 03:03:47,305] {docker.py:385} INFO - 396c31837116: Pulling fs layer
[2022-10-27 03:03:47,306] {docker.py:385} INFO - bb59ba756ca3: Pulling fs layer
[2022-10-27 03:03:47,307] {docker.py:385} INFO - 52d9f65633a2: Pulling fs layer
[2022-10-27 03:03:47,308] {docker.py:385} INFO - 7cdbc775d228: Pulling fs layer
[2022-10-27 03:03:47,309] {docker.py:385} INFO - 1832b9aadd75: Pulling fs layer
[2022-10-27 03:03:47,310] {docker.py:385} INFO - 4f4fb700ef54: Pulling fs layer
[2022-10-27 03:03:47,311] {docker.py:385} INFO - 616308593c75: Pulling fs layer
[2022-10-27 03:03:47,312] {docker.py:385} INFO - 1832b9aadd75: Waiting
[2022-10-27 03:03:47,313] {docker.py:385} INFO - 616308593c75: Waiting
[2022-10-27 03:03:47,315] {docker.py:385} INFO - 7cdbc775d228: Waiting
[2022-10-27 03:03:47,317] {docker.py:385} INFO - 4f4fb700ef54: Waiting
[2022-10-27 03:03:48,093] {docker.py:385} INFO - bb59ba756ca3: Downloading
[2022-10-27 03:03:48,094] {docker.py:385} INFO - bb59ba756ca3: Verifying Checksum
[2022-10-27 03:03:48,095] {docker.py:385} INFO - bb59ba756ca3: Download complete
[2022-10-27 03:03:48,096] {docker.py:385} INFO - 52d9f65633a2: Downloading
[2022-10-27 03:03:48,097] {docker.py:385} INFO - 52d9f65633a2: Verifying Checksum
[2022-10-27 03:03:48,098] {docker.py:385} INFO - 52d9f65633a2: Download complete
[2022-10-27 03:03:48,099] {docker.py:385} INFO - 396c31837116: Downloading
[2022-10-27 03:03:48,756] {docker.py:385} INFO - 396c31837116: Verifying Checksum
[2022-10-27 03:03:48,759] {docker.py:385} INFO - 396c31837116: Download complete
[2022-10-27 03:03:48,773] {docker.py:385} INFO - 396c31837116: Extracting
[2022-10-27 03:03:48,953] {docker.py:385} INFO - 396c31837116: Pull complete
[2022-10-27 03:03:48,955] {docker.py:385} INFO - bb59ba756ca3: Extracting
[2022-10-27 03:03:48,956] {docker.py:385} INFO - 7cdbc775d228: Downloading
[2022-10-27 03:03:48,957] {docker.py:385} INFO - 7cdbc775d228: Verifying Checksum
[2022-10-27 03:03:48,958] {docker.py:385} INFO - 7cdbc775d228: Download complete
[2022-10-27 03:03:48,959] {docker.py:385} INFO - bb59ba756ca3: Pull complete
[2022-10-27 03:03:48,960] {docker.py:385} INFO - 52d9f65633a2: Extracting
[2022-10-27 03:03:48,962] {docker.py:385} INFO - 1832b9aadd75: Downloading
[2022-10-27 03:03:48,963] {docker.py:385} INFO - 52d9f65633a2: Pull complete
[2022-10-27 03:03:49,165] {docker.py:385} INFO - 7cdbc775d228: Extracting
[2022-10-27 03:03:49,166] {docker.py:385} INFO - 7cdbc775d228: Pull complete
[2022-10-27 03:03:49,412] {docker.py:385} INFO - 4f4fb700ef54: Downloading
[2022-10-27 03:03:49,414] {docker.py:385} INFO - 4f4fb700ef54: Verifying Checksum
[2022-10-27 03:03:49,415] {docker.py:385} INFO - 4f4fb700ef54: Download complete
[2022-10-27 03:03:49,885] {docker.py:385} INFO - 616308593c75: Downloading
[2022-10-27 03:03:49,886] {docker.py:385} INFO - 616308593c75: Verifying Checksum
[2022-10-27 03:03:49,886] {docker.py:385} INFO - 616308593c75: Download complete
[2022-10-27 03:04:03,792] {docker.py:385} INFO - 1832b9aadd75: Verifying Checksum
[2022-10-27 03:04:03,793] {docker.py:385} INFO - 1832b9aadd75: Download complete
[2022-10-27 03:04:03,793] {docker.py:385} INFO - 1832b9aadd75: Extracting
[2022-10-27 03:04:12,912] {docker.py:385} INFO - 1832b9aadd75: Pull complete
[2022-10-27 03:04:12,913] {docker.py:385} INFO - 4f4fb700ef54: Extracting
[2022-10-27 03:04:12,914] {docker.py:385} INFO - 4f4fb700ef54: Pull complete
[2022-10-27 03:04:12,915] {docker.py:385} INFO - 616308593c75: Extracting
[2022-10-27 03:04:12,943] {docker.py:385} INFO - 616308593c75: Pull complete
[2022-10-27 03:04:12,944] {docker.py:380} INFO - Digest: sha256:3fe3e2c13a3d1f889b5e6127851b56734c3dbd0c268699e5fd3273631973c418
[2022-10-27 03:04:12,945] {docker.py:380} INFO - Status: Downloaded newer image for bde2020/spark-master:latest
[2022-10-27 03:04:12,945] {docker.py:247} INFO - Starting docker container from image bde2020/spark-master:latest
[2022-10-27 03:04:13,023] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-socket-proxy:2375/v1.37/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 387, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 254, in _run_image
    return self._run_image_with_mounts(self.mounts + [tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 298, in _run_image_with_mounts
    tty=self.tty,
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http://docker-socket-proxy:2375/v1.37/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/airflow/simple-app")
[2022-10-27 03:04:13,040] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=spark_job_dag, task_id=docker_command, execution_date=20221027T025726, start_date=20221027T030341, end_date=20221027T030413
[2022-10-27 03:04:13,083] {standard_task_runner.py:97} ERROR - Failed to execute job 83 for task docker_command (400 Client Error for http://docker-socket-proxy:2375/v1.37/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/airflow/simple-app"); 66)
[2022-10-27 03:04:13,122] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-27 03:04:13,154] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
