[2022-08-14 18:45:39,252] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.git_clone manual__2022-08-14T18:40:28.500537+00:00 [queued]>
[2022-08-14 18:45:39,266] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.git_clone manual__2022-08-14T18:40:28.500537+00:00 [queued]>
[2022-08-14 18:45:39,267] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-14 18:45:39,268] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-14 18:45:39,268] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-14 18:45:39,288] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): git_clone> on 2022-08-14 18:40:28.500537+00:00
[2022-08-14 18:45:39,297] {standard_task_runner.py:52} INFO - Started process 345 to run task
[2022-08-14 18:45:39,301] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spark_job_dag', 'git_clone', 'manual__2022-08-14T18:40:28.500537+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmphwqtc6kj', '--error-file', '/tmp/tmph5kg344z']
[2022-08-14 18:45:39,304] {standard_task_runner.py:80} INFO - Job 460: Subtask git_clone
[2022-08-14 18:45:39,383] {task_command.py:369} INFO - Running <TaskInstance: spark_job_dag.git_clone manual__2022-08-14T18:40:28.500537+00:00 [running]> on host f708cd78418a
[2022-08-14 18:45:39,476] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_job_dag
AIRFLOW_CTX_TASK_ID=git_clone
AIRFLOW_CTX_EXECUTION_DATE=2022-08-14T18:40:28.500537+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-14T18:40:28.500537+00:00
[2022-08-14 18:45:39,479] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-14 18:45:39,481] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'git clone https://github.com/marclamberti/simple-app.git /home/***/simple-app']
[2022-08-14 18:45:39,504] {subprocess.py:85} INFO - Output:
[2022-08-14 18:45:39,508] {subprocess.py:92} INFO - bash: line 1: git: command not found
[2022-08-14 18:45:39,509] {subprocess.py:96} INFO - Command exited with return code 127
[2022-08-14 18:45:39,534] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-08-14 18:45:39,542] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=spark_job_dag, task_id=git_clone, execution_date=20220814T184028, start_date=20220814T184539, end_date=20220814T184539
[2022-08-14 18:45:39,562] {standard_task_runner.py:97} ERROR - Failed to execute job 460 for task git_clone (Bash command failed. The command returned a non-zero exit code 127.; 345)
[2022-08-14 18:45:39,597] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-14 18:45:39,653] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
