[2022-08-15 22:13:27,689] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.git_clone scheduled__2022-08-14T18:19:09.951551+00:00 [queued]>
[2022-08-15 22:13:27,710] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.git_clone scheduled__2022-08-14T18:19:09.951551+00:00 [queued]>
[2022-08-15 22:13:27,711] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 22:13:27,712] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-15 22:13:27,713] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-15 22:13:27,732] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): git_clone> on 2022-08-14 18:19:09.951551+00:00
[2022-08-15 22:13:27,741] {standard_task_runner.py:52} INFO - Started process 166 to run task
[2022-08-15 22:13:27,746] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spark_job_dag', 'git_clone', 'scheduled__2022-08-14T18:19:09.951551+00:00', '--job-id', '464', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmp8y81hsm1', '--error-file', '/tmp/tmp5ppbj8pe']
[2022-08-15 22:13:27,759] {standard_task_runner.py:80} INFO - Job 464: Subtask git_clone
[2022-08-15 22:13:27,883] {task_command.py:369} INFO - Running <TaskInstance: spark_job_dag.git_clone scheduled__2022-08-14T18:19:09.951551+00:00 [running]> on host 0f67209b236a
[2022-08-15 22:13:27,995] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_job_dag
AIRFLOW_CTX_TASK_ID=git_clone
AIRFLOW_CTX_EXECUTION_DATE=2022-08-14T18:19:09.951551+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-14T18:19:09.951551+00:00
[2022-08-15 22:13:27,997] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-15 22:13:27,999] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'git clone https://github.com/marclamberti/simple-app.git /home/***/simple-app']
[2022-08-15 22:13:28,021] {subprocess.py:85} INFO - Output:
[2022-08-15 22:13:28,036] {subprocess.py:92} INFO - bash: line 1: git: command not found
[2022-08-15 22:13:28,037] {subprocess.py:96} INFO - Command exited with return code 127
[2022-08-15 22:13:28,060] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-08-15 22:13:28,067] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_job_dag, task_id=git_clone, execution_date=20220814T181909, start_date=20220815T221327, end_date=20220815T221328
[2022-08-15 22:13:28,081] {standard_task_runner.py:97} ERROR - Failed to execute job 464 for task git_clone (Bash command failed. The command returned a non-zero exit code 127.; 166)
[2022-08-15 22:13:28,136] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-15 22:13:28,196] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
